version: '3'

services:
  irb:
    build: ./
    image: irb
    networks:
      - traefik
    volumes:
      - ./data:/irb/data
    labels:
      traefik.docker.network: traefik
      traefik.enable: true
      traefik.port: 8080
      traefik.backend: irb
      traefik.frontend.rule: Host:patg.design

networks:
  traefik:
    external: true
